services:
  postgres:
    image: postgres:16-alpine
    container_name: wis_cms_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: wis_cms
      POSTGRES_USER: wis_admin
      POSTGRES_PASSWORD: wis_secret_2024
    ports:
      - "5433:5432"
    volumes:
      - wis_postgres_data:/var/lib/postgresql/data

volumes:
  wis_postgres_data: